=== sjrsay/deq/dra.dtd
<!ELEMENT dra (states, initial-state, transitions)>
<!ELEMENT states (state+)>
<!ELEMENT state (id, available-registers)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT available-registers (register*)>
<!ELEMENT initial-state (#PCDATA)>
<!ELEMENT transitions (transition*)>
<!ELEMENT transition (from, input, op, register, to)>
<!ELEMENT from (#PCDATA)>
<!ELEMENT input (#PCDATA)>
<!ELEMENT op (#PCDATA)>
<!ELEMENT register (#PCDATA)>
<!ELEMENT to (#PCDATA)>

=== sjrsay/deq/examples/cptR-3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dra SYSTEM "dra.dtd">
<dra>
  <states>
    <state>
      <id>q4</id>
      <available-registers>
        <register>3</register>
        <register>2</register>
        <register>1</register>
      </available-registers>
    </state>
    <state>
      <id>q1</id>
      <available-registers/>
    </state>
    <state>
      <id>q2</id>
      <available-registers>
        <register>3</register>
      </available-registers>
    </state>
    <state>
      <id>q3</id>
      <available-registers>
        <register>3</register>
        <register>2</register>
      </available-registers>
    </state>
  </states>
  <initial-state>q1</initial-state>
  <transitions>
    <transition>
      <from>q1</from>
      <input>populate</input>
      <op>LFresh</op>
      <register>3</register>
      <to>q2</to>
    </transition>
    <transition>
      <from>q2</from>
      <input>populate</input>
      <op>LFresh</op>
      <register>2</register>
      <to>q3</to>
    </transition>
    <transition>
      <from>q3</from>
      <input>populate</input>
      <op>LFresh</op>
      <register>1</register>
      <to>q4</to>
    </transition>
    <transition>
      <from>q2</from>
      <input>populate</input>
      <op>Read</op>
      <register>3</register>
      <to>q2</to>
    </transition>
    <transition>
      <from>q3</from>
      <input>populate</input>
      <op>Read</op>
      <register>3</register>
      <to>q3</to>
    </transition>
    <transition>
      <from>q3</from>
      <input>populate</input>
      <op>Read</op>
      <register>2</register>
      <to>q3</to>
    </transition>
    <transition>
      <from>q4</from>
      <input>t3</input>
      <op>LFresh</op>
      <register>3</register>
      <to>q4</to>
    </transition>
    <transition>
      <from>q4</from>
      <input>t2</input>
      <op>LFresh</op>
      <register>2</register>
      <to>q4</to>
    </transition>
    <transition>
      <from>q4</from>
      <input>t1</input>
      <op>LFresh</op>
      <register>1</register>
      <to>q4</to>
    </transition>
    <transition>
      <from>q4</from>
      <input>t3</input>
      <op>Read</op>
      <register>3</register>
      <to>q4</to>
    </transition>
    <transition>
      <from>q4</from>
      <input>t3</input>
      <op>Read</op>
      <register>2</register>
      <to>q4</to>
    </transition>
    <transition>
      <from>q4</from>
      <input>t3</input>
      <op>Read</op>
      <register>1</register>
      <to>q4</to>
    </transition>
    <transition>
      <from>q4</from>
      <input>t2</input>
      <op>Read</op>
      <register>3</register>
      <to>q4</to>
    </transition>
    <transition>
      <from>q4</from>
      <input>t2</input>
      <op>Read</op>
      <register>2</register>
      <to>q4</to>
    </transition>
    <transition>
      <from>q4</from>
      <input>t2</input>
      <op>Read</op>
      <register>1</register>
      <to>q4</to>
    </transition>
    <transition>
      <from>q4</from>
      <input>t1</input>
      <op>Read</op>
      <register>3</register>
      <to>q4</to>
    </transition>
    <transition>
      <from>q4</from>
      <input>t1</input>
      <op>Read</op>
      <register>2</register>
      <to>q4</to>
    </transition>
    <transition>
      <from>q4</from>
      <input>t1</input>
      <op>Read</op>
      <register>1</register>
      <to>q4</to>
    </transition>
  </transitions>
</dra>

=== sjrsay/deq/examples/lrstack-alt-3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dra SYSTEM "dra.dtd">
<dra>
  <states>
    <state>
      <id>q1</id>
      <available-registers/>
    </state>
    <state>
      <id>q2</id>
      <available-registers>
        <register>1</register>
      </available-registers>
    </state>
    <state>
      <id>q3</id>
      <available-registers>
        <register>2</register>
      </available-registers>
    </state>
    <state>
      <id>q4</id>
      <available-registers>
        <register>2</register>
      </available-registers>
    </state>
    <state>
      <id>q5</id>
      <available-registers>
        <register>1</register>
        <register>2</register>
      </available-registers>
    </state>
    <state>
      <id>q6</id>
      <available-registers>
        <register>2</register>
        <register>3</register>
      </available-registers>
    </state>
    <state>
      <id>q7</id>
      <available-registers>
        <register>2</register>
        <register>3</register>
      </available-registers>
    </state>
    <state>
      <id>q8</id>
      <available-registers>
        <register>1</register>
        <register>2</register>
        <register>3</register>
      </available-registers>
    </state>
    <state>
      <id>q9</id>
      <available-registers>
        <register>2</register>
        <register>3</register>
        <register>4</register>
      </available-registers>
    </state>
    <state>
      <id>q10</id>
      <available-registers>
        <register>2</register>
        <register>3</register>
        <register>4</register>
      </available-registers>
    </state>
    <state>
      <id>q11</id>
      <available-registers>
        <register>1</register>
        <register>2</register>
        <register>3</register>
        <register>4</register>
      </available-registers>
    </state>
    <state>
      <id>q12</id>
      <available-registers>
        <register>1</register>
        <register>2</register>
        <register>3</register>
        <register>4</register>
      </available-registers>
    </state>
  </states>
  <initial-state>q1</initial-state>
  <transitions>
    <transition>
      <from>q1</from>
      <input>IPush</input>
      <op>LFresh</op>
      <register>2</register>
      <to>q3</to>
    </transition>
    <transition>
      <from>q4</from>
      <input>IPush</input>
      <op>LFresh</op>
      <register>3</register>
      <to>q6</to>
    </transition>
    <transition>
      <from>q7</from>
      <input>IPush</input>
      <op>LFresh</op>
      <register>4</register>
      <to>q9</to>
    </transition>
    <transition>
      <from>q4</from>
      <input>ISkip</input>
      <op>LFresh</op>
      <register>1</register>
      <to>q5</to>
    </transition>
    <transition>
      <from>q7</from>
      <input>ISkip</input>
      <op>LFresh</op>
      <register>1</register>
      <to>q8</to>
    </transition>
    <transition>
      <from>q10</from>
      <input>ISkip</input>
      <op>LFresh</op>
      <register>1</register>
      <to>q11</to>
    </transition>
    <transition>
      <from>q5</from>
      <input>OPop</input>
      <op>Read</op>
      <register>2</register>
      <to>q1</to>
    </transition>
    <transition>
      <from>q8</from>
      <input>OPop</input>
      <op>Read</op>
      <register>3</register>
      <to>q4</to>
    </transition>
    <transition>
      <from>q11</from>
      <input>OPop</input>
      <op>Read</op>
      <register>4</register>
      <to>q7</to>
    </transition>
    <transition>
      <from>q3</from>
      <input>OSkip</input>
      <op>Read</op>
      <register>2</register>
      <to>q4</to>
    </transition>
    <transition>
      <from>q6</from>
      <input>OSkip</input>
      <op>Read</op>
      <register>3</register>
      <to>q7</to>
    </transition>
    <transition>
      <from>q9</from>
      <input>OSkip</input>
      <op>Read</op>
      <register>4</register>
      <to>q10</to>
    </transition>
    <transition>
      <from>q1</from>
      <input>ISkip</input>
      <op>LFresh</op>
      <register>1</register>
      <to>q2</to>
    </transition>
    <transition>
      <from>q2</from>
      <input>OSkip</input>
      <op>Read</op>
      <register>1</register>
      <to>q1</to>
    </transition>
    <transition>
      <from>q10</from>
      <input>IPush</input>
      <op>LFresh</op>
      <register>1</register>
      <to>q12</to>
    </transition>
    <transition>
      <from>q12</from>
      <input>OSkip</input>
      <op>Read</op>
      <register>1</register>
      <to>q10</to>
    </transition>
  </transitions>
</dra>

=== sjrsay/deq/examples/gloloL-3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dra SYSTEM "dra.dtd">
<dra>
  <states>
    <state>
      <id>q4</id>
      <available-registers>
        <register>1</register>
        <register>2</register>
        <register>3</register>
      </available-registers>
    </state>
    <state>
      <id>q0</id>
      <available-registers/>
    </state>
    <state>
      <id>q1</id>
      <available-registers>
        <register>1</register>
      </available-registers>
    </state>
    <state>
      <id>q2</id>
      <available-registers>
        <register>1</register>
        <register>2</register>
      </available-registers>
    </state>
    <state>
      <id>q3</id>
      <available-registers>
        <register>1</register>
        <register>2</register>
        <register>3</register>
      </available-registers>
    </state>
  </states>
  <initial-state>q0</initial-state>
  <transitions>
    <transition>
      <from>q3</from>
      <input>input</input>
      <op>LFresh</op>
      <register>3</register>
      <to>q4</to>
    </transition>
    <transition>
      <from>q0</from>
      <input>input</input>
      <op>GFresh</op>
      <register>1</register>
      <to>q1</to>
    </transition>
    <transition>
      <from>q1</from>
      <input>input</input>
      <op>GFresh</op>
      <register>2</register>
      <to>q2</to>
    </transition>
    <transition>
      <from>q2</from>
      <input>input</input>
      <op>GFresh</op>
      <register>3</register>
      <to>q3</to>
    </transition>
  </transitions>
</dra>
